name: hongyan_im
description: 鸿雁IM-基础功能
version: 1.0.0
homepage: https://github.com/addcnos/Hongyan-Flutter-SDK

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.9
  web_socket_channel: ^1.1.0
  crypto: ^2.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - test.jpg